import type { LayoutId } from '../types/schema';
import { normalizeLayoutId } from './aliases';

export const layoutNames: Record<string, string> = {
  cover: '封面页',
  toc: '目录页',
  title_content: '标题+正文',
  title_bullets: '标题+要点',
  two_column: '左右双栏',
  process_steps: '流程步骤',
  ending: '结束页',
  section_title: '章节标题',
  image_full: '全图页',
  quote: '引用页',
  vocational_bullets: '要点讲解',
  vocational_content: '内容讲解',
  vocational_comparison: '对比讲解',
  learning_objectives: '学习目标',
  theory_explanation: '理论推导',
  academic_narrative: '长文叙述',
  case_study: '案例分析',
  comparison_table: '对比分析',
  diagram_illustration: '原理图解',
  academic_practice: '随堂实训',
  ending_academic: '课程结束',
  cover_academic: '学术封面',
  toc_academic: '学术目录',
  // Modern scheme - 现代创新方案
  sidebar_card: '左侧导航卡片',
  dark_math: '科技深色分割',
  flow_process: '横向流程图解',
  overlap: '破格叠加',
  grid_matrix: '矩阵宫格',
  diagonal_split: '动感斜切',
  concentric_focus: '同心聚焦',
  vertical_timeline: '垂直脉络',
  tri_column: '三柱支撑',
  cinematic_overlay: '未来沉浸全图',
  // Interactive scheme - 互动探究型
  agenda_path: '学程地图',
  case_discussion: '案例研讨',
  cover_interactive: '导入封面',
  ending_interactive: '评价结语',
  feedback_poll: '即时反馈',
  group_collab: '协作任务',
  group_activity: '小组活动',
  mind_map_structure: '知识脑图',
  mind_map: '思维导图',
  quiz_interaction: '交互测验',
  quiz_check: '课堂测验',
  role_play_scenario: '情境模拟',
  discussion_prompt: '讨论引导',
  agenda_interactive: '互动议程',
  warmup_inquiry: '课前探究',
  warmup_question: '热身提问',
  poll_interactive: '投票互动',
  story_narrative: '故事叙述',
  // Modern Management - 现代管理型
  business_canvas: '业务看板',
  comparison_matrix: '标准对比',
  cover_modern: '管理封面',
  ending_modern: '总结展望',
  legal_regulation: '规则解析',
  org_structure_flow: '组织架构',
  process_sop_standard: '标杆流程',
  stat_report: '运行分析',
  strategic_pillars: '核心支柱',
  toc_modern: '专业导览',
  // Vocational Practice - 精益实操型
  checklist_verification: '核查清单',
  common_faults: '故障排除',
  cover_practical: '实训封面',
  detail_specs: '零件精度',
  ending_practical: '实训总结',
  equipment_orientation: '设备认知',
  safety_protocol: '安全禁令',
  sop_vertical_steps: 'SOP手册',
  task_instruction: '工单指令',
  technical_tip: '讲师小结',
  // Engineering Logic - 技术逻辑型
  arch_blocks: '技术架构',
  cover_tech: '技术封面',
  ending_tech: '技术演进',
  flow_logic_sequence: '逻辑时序',
  param_dashboard: '性能看板',
  protocol_analysis: '协议拆解',
  requirement_specs: '需求规格',
  system_comparison: '选型对比',
  tech_principle: '技术原理',
  toc_tech: '技术大纲',
  // Industry Showcase - 行业展示型
  cover_visual: '视觉封面',
  timeline_navigation: '时间导航',
  timeline: '时间轴',
  hero_image: '主视觉大图',
  gallery_grid: '图库网格',
  before_after: '前后对比',
  infographic: '信息图解',
  split_screen: '分屏对照',
  video_placeholder: '视频占位',
  portfolio_showcase: '作品展示',
  portfolio: '作品集展示',
  ending_visual: '视觉收尾',
  case_before_after: '修缮对比',
  cover_field: '现场封面',
  ending_field: '现场收束',
  field_observation: '现场观测',
  gallery_professional: '专业图库',
  infographic_flow: '图解流',
  portfolio_industry: '成果品鉴',
  site_survey: '踏勘报告',
  specimen_detail: '标本特写',
  timeline_evolution: '演进轴线',
  checklist_practical: '操作清单',
  safety_notice: '安全提示',
  equipment_intro: '设备介绍',
  step_by_step: '步骤拆解',
  detail_zoom: '细节放大',
  common_mistakes: '常见错误',
  tip_trick: '技巧提示',
  practice_exercise: '练习实操',
  // Edu dark scheme
  edu_cover: '职教通用封面',
  edu_toc: '模块导览',
  edu_tri_compare: '三维对比',
  edu_core_hub: '核心框架',
  edu_timeline_steps: '实施路径',
  edu_logic_flow: '教学链路',
  edu_data_board: '数据看板',
  edu_summary: '反思评价',
  edu_qa_case: '典型案例',
};

export const getLayoutDisplayName = (layoutId?: string | null): string => {
  if (!layoutId) {
    return '未知布局';
  }

  const directName = layoutNames[layoutId];
  if (directName) {
    return directName;
  }

  const normalizedId = normalizeLayoutId(layoutId as LayoutId);
  return layoutNames[normalizedId] || layoutId;
};
