"""Configuration builder for the standalone home characters feature."""

from __future__ import annotations

from .schemas import HomeCharacterConfig, HomeCharactersConfig


def get_home_characters_config() -> HomeCharactersConfig:
    """Return the lightweight interaction config consumed by the homepage."""

    return HomeCharactersConfig(
        eyebrow="Lightweight Home Interaction",
        title="四位会盯着你写提示词的编辑",
        description=(
            "这是一个独立功能模块。桌面端启用轻量交互，输入时角色会轻微靠近，"
            "空闲时只保留低频眨眼与视线跟随。"
        ),
        footnote="单监听、低频动画、仅首页引用，不参与生成链路。",
        scene_width=1000,
        scene_height=340,
        floor_height=1,
        chips=["桌面端启用", "低资源", "独立模块"],
        characters=[
            HomeCharacterConfig(
                id="purple-editor",
                shape="block",
                width=126,
                height=172,
                left=70,
                bottom=228,
                background="#7d63e5",
                border_radius="22px 22px 16px 16px",
                layer=1,
                eye_style="eyeball",
                eye_top=34,
                eye_left=39,
                eye_gap=20,
                eye_size=14,
                pupil_size=5,
                pupil_color="#595463",
                max_face_x=10,
                max_face_y=8,
                max_skew=4.5,
                face_x_factor=0.8,
                face_y_factor=0.8,
                skew_factor=0.7,
                focus_shift_x=2,
                focus_shift_y=2,
                focus_skew=-4.2,
                focus_height_delta=8,
                ready_shift_y=0,
                blink_enabled=True,
            ),
            HomeCharacterConfig(
                id="black-editor",
                shape="rounded_block",
                width=94,
                height=132,
                left=860,
                bottom=294,
                background="#262a35",
                border_radius="20px 20px 14px 14px",
                layer=2,
                eye_style="eyeball",
                eye_top=16,
                eye_left=18,
                eye_gap=15,
                eye_size=12,
                pupil_size=4,
                pupil_color="#5f6470",
                max_face_x=8,
                max_face_y=7,
                max_skew=4.2,
                face_x_factor=0.7,
                face_y_factor=0.65,
                skew_factor=0.65,
                focus_shift_x=1,
                focus_shift_y=-4,
                focus_skew=4.0,
                focus_height_delta=10,
                ready_shift_y=0,
                blink_enabled=True,
            ),
            HomeCharacterConfig(
                id="orange-editor",
                shape="arch",
                width=132,
                height=96,
                left=-68,
                bottom=102,
                background="#e38c58",
                border_radius="64px 64px 18px 18px",
                layer=3,
                eye_style="eyeball",
                eye_top=24,
                eye_left=43,
                eye_gap=16,
                eye_size=10,
                pupil_size=5,
                eye_color="#fff7ef",
                pupil_color="#5d4538",
                max_face_x=6,
                max_face_y=5,
                max_skew=3.2,
                face_x_factor=0.55,
                face_y_factor=0.5,
                skew_factor=0.45,
                focus_shift_x=-1,
                focus_shift_y=0,
                focus_skew=-2.8,
                ready_shift_y=0,
            ),
            HomeCharacterConfig(
                id="yellow-editor",
                shape="arch",
                width=112,
                height=112,
                left=966,
                bottom=98,
                background="#d0b93f",
                border_radius="56px 56px 18px 18px",
                layer=4,
                eye_style="eyeball",
                eye_top=20,
                eye_left=22,
                eye_gap=14,
                eye_size=10,
                pupil_size=5,
                eye_color="#fffbe8",
                pupil_color="#564f2a",
                mouth_top=46,
                mouth_left=26,
                mouth_width=40,
                mouth_height=3,
                max_face_x=6,
                max_face_y=5,
                max_skew=3.0,
                face_x_factor=0.55,
                face_y_factor=0.5,
                skew_factor=0.45,
                focus_shift_x=0,
                focus_shift_y=0,
                focus_skew=2.8,
                ready_shift_y=0,
            ),
        ],
    )
