import { render, screen } from '@testing-library/react';
import { describe, expect, it, vi } from 'vitest';

import { HomeCharactersFeature } from './components/HomeCharactersFeature';

vi.mock('./hooks/useHomeCharactersConfig', () => ({
  useHomeCharactersConfig: () => ({
    eyebrow: 'Lightweight Home Interaction',
    title: '四位会盯着你写提示词的编辑',
    description: '这是一个独立功能模块。桌面端启用轻量交互，输入时角色会轻微靠近。',
    footnote: '单监听、低频动画、仅首页引用，不参与生成链路。',
    scene_width: 1000,
    scene_height: 340,
    floor_height: 1,
    chips: ['桌面端启用', '低资源', '独立模块'],
    characters: [
      {
        id: 'purple-editor',
        shape: 'block',
        width: 126,
        height: 172,
        left: 78,
        bottom: 224,
        layer: 1,
        background: '#8770e2',
        border_radius: '22px 22px 16px 16px',
        eye_style: 'eyeball',
        eye_top: 34,
        eye_left: 39,
        eye_gap: 20,
        eye_size: 14,
        pupil_size: 5,
        eye_color: 'white',
        pupil_color: '#595463',
        mouth_height: 4,
        max_face_x: 10,
        max_face_y: 8,
        max_skew: 4.5,
        face_x_factor: 0.8,
        face_y_factor: 0.8,
        skew_factor: 0.7,
        focus_shift_x: 8,
        focus_shift_y: 8,
        focus_skew: -4.2,
        focus_height_delta: 8,
        ready_shift_y: 0,
        blink_enabled: true,
      },
      {
        id: 'black-editor',
        shape: 'rounded_block',
        width: 94,
        height: 132,
        left: 828,
        bottom: 224,
        layer: 2,
        background: '#2e3038',
        border_radius: '20px 20px 14px 14px',
        eye_style: 'eyeball',
        eye_top: 28,
        eye_left: 18,
        eye_gap: 15,
        eye_size: 12,
        pupil_size: 4,
        eye_color: 'white',
        pupil_color: '#5f6470',
        mouth_height: 4,
        max_face_x: 8,
        max_face_y: 7,
        max_skew: 4.2,
        face_x_factor: 0.7,
        face_y_factor: 0.65,
        skew_factor: 0.65,
        focus_shift_x: -7,
        focus_shift_y: 8,
        focus_skew: 4,
        focus_height_delta: 0,
        ready_shift_y: 0,
        blink_enabled: true,
      },
      {
        id: 'orange-editor',
        shape: 'arch',
        width: 132,
        height: 96,
        left: -78,
        bottom: 84,
        layer: 3,
        background: '#e8a171',
        border_radius: '64px 64px 18px 18px',
        eye_style: 'pupil',
        eye_top: 28,
        eye_left: 49,
        eye_gap: 18,
        eye_size: 8,
        pupil_size: 8,
        eye_color: 'transparent',
        pupil_color: '#755d4c',
        mouth_height: 4,
        max_face_x: 6,
        max_face_y: 5,
        max_skew: 3.2,
        face_x_factor: 0.55,
        face_y_factor: 0.5,
        skew_factor: 0.45,
        focus_shift_x: 7,
        focus_shift_y: 0,
        focus_skew: -2.8,
        focus_height_delta: 0,
        ready_shift_y: 0,
        blink_enabled: false,
      },
      {
        id: 'yellow-editor',
        shape: 'arch',
        width: 112,
        height: 112,
        left: 966,
        bottom: 80,
        layer: 4,
        background: '#d8c354',
        border_radius: '56px 56px 18px 18px',
        eye_style: 'pupil',
        eye_top: 24,
        eye_left: 27,
        eye_gap: 16,
        eye_size: 8,
        pupil_size: 8,
        eye_color: 'transparent',
        pupil_color: '#6f674f',
        mouth_top: 46,
        mouth_left: 26,
        mouth_width: 40,
        mouth_height: 3,
        max_face_x: 6,
        max_face_y: 5,
        max_skew: 3,
        face_x_factor: 0.55,
        face_y_factor: 0.5,
        skew_factor: 0.45,
        focus_shift_x: -6,
        focus_shift_y: 0,
        focus_skew: 2.8,
        focus_height_delta: 0,
        ready_shift_y: 0,
        blink_enabled: false,
      },
    ],
  }),
}));

describe('HomeCharactersFeature', () => {
  it('renders four decorative character figures', () => {
    render(<HomeCharactersFeature isPromptFocused={false} hasPromptContent={false} />);

    expect(screen.getAllByTestId('home-character-figure')).toHaveLength(4);
  });
});
